import { WhiteboardEvent } from "../core";

export const seedWhiteboardEvents: WhiteboardEvent[] = [
  {
    id: "evt_1",
    boardId: "board_1",
    branchId: "main",
    parentEventId: null,
    actor: { type: "human", id: "aditya", label: "Aditya" },
    type: "board.created",
    timestamp: "2026-03-17T16:00:00.000Z",
    payload: {
      title: "Replayabl Whiteboard Demo",
      description: "A minimal replay-first browser demo for human + AI collaboration.",
    },
  },
  {
    id: "evt_2",
    boardId: "board_1",
    branchId: "main",
    parentEventId: "evt_1",
    actor: { type: "human", id: "aditya", label: "Aditya" },
    type: "node.created",
    timestamp: "2026-03-17T16:00:05.000Z",
    payload: {
      nodeId: "node_problem",
      kind: "note",
      x: 100,
      y: 100,
      width: 220,
      height: 120,
      text: "Legacy apps treat AI as an outsider.",
      style: {
        backgroundColor: "#FEF3C7",
        borderColor: "#F59E0B",
      },
    },
  },
  {
    id: "evt_3",
    boardId: "board_1",
    branchId: "main",
    parentEventId: "evt_2",
    actor: { type: "human", id: "aditya", label: "Aditya" },
    type: "node.created",
    timestamp: "2026-03-17T16:00:07.000Z",
    payload: {
      nodeId: "node_solution",
      kind: "note",
      x: 420,
      y: 100,
      width: 260,
      height: 120,
      text: "Replayabl gives humans and LLMs the same shared event substrate.",
      style: {
        backgroundColor: "#DBEAFE",
        borderColor: "#3B82F6",
      },
    },
  },
  {
    id: "evt_4",
    boardId: "board_1",
    branchId: "main",
    parentEventId: "evt_3",
    actor: { type: "human", id: "aditya", label: "Aditya" },
    type: "edge.created",
    timestamp: "2026-03-17T16:00:10.000Z",
    payload: {
      edgeId: "edge_1",
      fromNodeId: "node_problem",
      toNodeId: "node_solution",
      label: "motivation",
    },
  },
  {
    id: "evt_5",
    boardId: "board_1",
    branchId: "main",
    parentEventId: "evt_4",
    actor: { type: "llm", id: "assistant", label: "Kandy" },
    type: "proposal.created",
    timestamp: "2026-03-17T16:00:15.000Z",
    payload: {
      proposalId: "proposal_1",
      title: "Group the core idea",
      description: "Cluster the existing nodes and add a follow-up node for implementation focus.",
      proposedEvents: [
        {
          id: "evt_6",
          boardId: "board_1",
          branchId: "main",
          parentEventId: "evt_5",
          actor: { type: "llm", id: "assistant", label: "Kandy" },
          type: "group.created",
          timestamp: "2026-03-17T16:00:16.000Z",
          payload: {
            groupId: "group_core_idea",
            title: "Core Thesis",
            memberIds: ["node_problem", "node_solution"],
            style: {
              backgroundColor: "#F8FAFC",
              borderColor: "#94A3B8",
            },
          },
        },
        {
          id: "evt_7",
          boardId: "board_1",
          branchId: "main",
          parentEventId: "evt_6",
          actor: { type: "llm", id: "assistant", label: "Kandy" },
          type: "node.created",
          timestamp: "2026-03-17T16:00:18.000Z",
          payload: {
            nodeId: "node_next_step",
            kind: "note",
            x: 760,
            y: 220,
            width: 220,
            height: 110,
            text: "Ship a small whiteboard demo to prove the replay loop.",
            style: {
              backgroundColor: "#DCFCE7",
              borderColor: "#22C55E",
            },
          },
        },
        {
          id: "evt_8",
          boardId: "board_1",
          branchId: "main",
          parentEventId: "evt_7",
          actor: { type: "llm", id: "assistant", label: "Kandy" },
          type: "edge.created",
          timestamp: "2026-03-17T16:00:20.000Z",
          payload: {
            edgeId: "edge_2",
            fromNodeId: "node_solution",
            toNodeId: "node_next_step",
            label: "next",
            style: {
              color: "#22C55E",
            },
          },
        },
      ],
    },
    meta: {
      source: "agent",
      approvalStatus: "pending",
      reasoning: "Grouping the current nodes and adding the next step clarifies the narrative.",
      tags: ["proposal", "demo"],
    },
  },
];
