/**
 * Validation Result Type
 * 
 * Supports the Validation + Policy Layer. Instead of a simple boolean,
 * it returns detailed failures to feed rejection context back to LLMs or UIs.
 */
export type ValidationFailure = {
  code: string;
  message: string;
  path?: string[];
};

export type ValidationResult<T> = 
  | { success: true; data: T }
  | { success: false; errors: ValidationFailure[] };

/**
 * Command Envelope
 * 
 * Represents an intent to change state. Generated by the Ingress layer.
 * Note the explicit requirement of `targetVersion` or `targetEventId` to support OCC.
 */
export type CommandEnvelope<TType extends string, TPayload> = {
  type: TType;
  payload: TPayload;
  actorId: string;
  boardId: string;
  branchId: string;
  
  // Optimistic Concurrency Control (OCC) markers
  targetEventId?: string; // The last event ID the client saw
  targetSequence?: number; // The expected sequence number
};

/**
 * Advanced Event Envelope (Framework Level)
 * 
 * Incorporates Optimistic Concurrency Control (OCC) and Schema Versioning.
 */
export type FrameworkEventEnvelope<TType extends string, TPayload> = {
  id: string; // UUID/ULID
  boardId: string;
  branchId: string;
  
  type: TType;
  payload: TPayload;
  
  actor: {
    id: string;
    type: "human" | "agent" | "system";
  };
  
  timestamp: number;
  
  // OCC & Ordering
  parentEventId: string; // Causal consistency
  sequence: number;      // Deterministic replay ordering
  
  // Versioning & Upcasting
  schemaVersion: number;
  
  // Provenance & Policy
  meta?: {
    source?: "ui" | "agent" | "import" | "system";
    reasoning?: string;
    approvalStatus?: "pending" | "approved" | "rejected" | "not_required";
    isEncrypted?: boolean; // Crypto-Shredding indicator
  };
};

/**
 * Event Upcaster Interface
 * 
 * Responsible for migrating older event schemas to the newest version 
 * in-memory during replay, ensuring Reducers only ever deal with the latest type.
 */
export interface EventUpcaster<TEvent = any> {
  fromVersion: number;
  toVersion: number;
  eventType: string;
  
  upcast(oldEvent: any): TEvent;
}

/**
 * Policy / Gate Interface
 * 
 * Defines the contract for authorization and business logic checks 
 * before a command can be committed as an event.
 */
export interface CommandPolicy<TCommand = any> {
  evaluate(command: TCommand, currentState: any): ValidationResult<TCommand>;
}

import { WhiteboardEvent } from "./events";
import { WhiteboardState } from "./state";
import { replayEvents } from "./reducer";

export class Framework {
  private events: WhiteboardEvent[] = [];
  private state: WhiteboardState | null = null;
  private listeners: Set<(state: WhiteboardState, events: WhiteboardEvent[]) => void> = new Set();
  
  constructor(initialEvents: WhiteboardEvent[] = []) {
    this.events = initialEvents;
    this.state = replayEvents(initialEvents);
  }

  getEvents() {
    return this.events;
  }
  
  getState() {
    if (!this.state) {
      this.state = replayEvents(this.events);
    }
    return this.state;
  }
  
  appendEvent(event: WhiteboardEvent) {
    this.events.push(event);
    this.state = replayEvents(this.events);
    this.notify();
  }
  
  subscribe(listener: (state: WhiteboardState, events: WhiteboardEvent[]) => void) {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }
  
  private notify() {
    const s = this.getState();
    this.listeners.forEach(l => l(s, this.events));
  }
}


